language: cpp
os: linux
dist: trusty
sudo: false

# This only exists because of a bug: https://github.com/travis-ci/travis-ci/issues/4681
env:
  matrix:
    - EMPTY_JOB_IN_TRAVIS_CI=1

addons:
  apt:
    packages: &default_dep
      - clang-6.0
      - libclang-6.0-dev
      - clang-tools-6.0
      - llvm-6.0
      - llvm-6.0-dev
      - zlib1g-dev
      - libxml2-dev
      - libedit-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0

matrix:
  exclude:
    - env: EMPTY_JOB_IN_TRAVIS_CI=1
  include:
    - env: CLANG_VERSION=6.0 BUILD_TYPE=Release UNIT_TEST=0

before_install:
  - export DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependency" 
  - mkdir -p ${DEPENDENCY_DIR}
  - cd ${DEPENDENCY_DIR}

install:
  - |
    CMAKE_URL="https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir -p cmake
    travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPENDENCY_DIR}/cmake/bin:${PATH}
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - |
    if [[ -n $CLANG_VERSION ]] ; then 
      export CXX="clang++-${CLANG_VERSION}"
      export CC="clang-${CLANG_VERSION}"
    fi
  - export BUILD_DIR="build_${CC}"
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}

script: 
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build .
  - |
    if [[ $UNIT_TEST == 1 ]] ; then 
      ctest
    fi

branches:
  only:
    - master
